application:
  actions: actions
  web: app
  runtimeManifest:
    packages:
      test-poc-aio:
        license: Apache-2.0
        actions:
          generic:
            function: actions/generic/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          publish-events:
            function: actions/publish-events/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              apiKey: $SERVICE_API_KEY
            annotations:
              require-adobe-auth: true
              final: true
  hooks:
    pre-app-build: npm install
    post-app-build: npm run build:actions
    build-actions: npm run test
    build-static: npm run build